[package]
name = "miden-client"
version = "0.1.0"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-client"
keywords = ["miden", "client"]
edition = "2021"
rust-version = "1.67"

[features]
default = ["std"]
std = ["crypto/std", "objects/std"]
testing = ["objects/testing", "mock"]

[dependencies]
clap = { version = "4.3" , features = ["derive"] }
crypto = { package = "miden-crypto", git = "https://github.com/0xPolygonMiden/crypto", branch = "next", default-features = false }
lazy_static = "1.4.0"
objects = { package = "miden-objects", git = "https://github.com/0xPolygonMiden/miden-base", branch = "main", features = ["serde"] }
miden_lib = { package = "miden-lib", git = "https://github.com/0xPolygonMiden/miden-base", branch = "main", default-features = false }
miden_node_proto = { package = "miden-node-proto", git = "https://github.com/0xPolygonMiden/miden-node.git", branch = "main", default-features = false }
mock = { package = "miden-mock", git = "https://github.com/0xPolygonMiden/miden-base", branch = "main", default-features = false, optional = true }
rusqlite = { version = "0.29.0", features = ["bundled"] }
rusqlite_migration = { version = "1.0" }
rand = { version = "0.8.5" }
serde = {version = "1.0", features = ["derive"]}
serde_json = { version = "1.0", features = ["raw_value"] }
tonic = { version = "0.10" }
tokio = { version = "1.29", features = ["rt-multi-thread", "net", "macros"] }
comfy-table = "7.1.0"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"
escargot = "0.5.8"
uuid = { version = "1.6.1", features = ["serde", "v4"] }
mock = { package = "miden-mock", git = "https://github.com/0xPolygonMiden/miden-base", branch = "main", default-features = false }
vm-processor = { package = "miden-processor", git = "https://github.com/0xPolygonMiden/miden-vm.git", branch = "next", default-features = false }
